name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read

env:
  GO_VERSION: 1.19

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          args: --timeout 3m0s
